version: '3.7'
services:
  redimne:
    image: redmine:3
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: root
      REDMINE_DB_ENCODING: utf8mb4
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine

